### ISSUE TITLE
Connecting to OPEN networks

### ISSUE THREAD

**Issue by anthonywebb** [mebrunet/softap-setup-page#1]
I have been playing around with the code on my photon, and it is working great on networks with a password, but with open networks it doesnt seem to work.  I modified the code to only include pwd if network.sec == 0 as they do here https://github.com/spark/softap-setup-js/blob/master/index.js#L172, but I still am not getting anywhere.  I will note that the particle ios app will connect the photon to an open network.  Gotta be something minor.

**Comment by anthonywebb** [comment]
This appears to be a safari only bug (which is unfortunate because it is the default browser on iOS)

What I am trying to do is setup via the web (http://fuel.tetontechnology.com/setup/)
http://fuel.tetontechnology.com/setup/script.js

I am finding that connecting to secure network works fine in safari, but OPEN networks do not work in safari.  But, with the same code both secure and open networks work in chrome just fine, same for both mobile and desktops alike, argh!

**Comment by mebrunet** [comment]
First of all, I'm very happy that you're using and testing this! Thanks for the feedback.

I don't have Safari, so this might be a little harder for me to test. Do you have access to the raw request sent by the XMLHttpRequest object on Safari? On Chrome you can use the built-in developer console, is there an equivalent on Safari? You might need a plug-in. If so check to see the differences in the underlying request sent. That should give me a hint about what to change.

**Comment by anthonywebb** [comment]
Let me dig around a little bit @mebrunet gotta be something small.  

Another question was, is this page intended to be served from the device itself?  I moved the src folder to the web so I could host/hackon it.  I had to tweak mine a little bit so that it wasnt querying for the deviceid onload (because the user had to first connect to the device after loading the page from the public internet.  I also simplified the UI a bit to accomplish the single task of getting the device online. (no deviceid, etc)

**Comment by mebrunet** [comment]
Great, I appreciate.

Yes - I'm currently serving this page from the device itself, hence `compress.py` and `softap_pages.h`. This [post](https://community.particle.io/t/photon-softap-usage/11035/108) gives more detail on the vision.

**Comment by anthonywebb** [comment]
So after some more tests, it appears that safari does not work at all, but chrome works just fine.  I spent some time looking over the requests and there isnt anything glaring that I can see.. Frustrating.

**Comment by mebrunet** [comment]
What version of Safari? Also when you say "not at all" you mean regardless of whether the network is password protected or not Safari doesn't work?

**Comment by anthonywebb** [comment]
I am testing Safari Version 9.0 (10601.1.50), but I am not having any luck on my iphone (iOS 8.4) either.  Neither will work on any type of network (open or secured).  All my GET's work fine on all browsers, just those POST's that fail in safari based browsers, which is a bummer because iOS is pretty prevalent and that is the default browser on those devices.

The POST request doesnt time out, in fact it does return a valid json response just like chrome does, it just doesnt appear to save the credentials we sent in the POST.  Everything looks good too, content-type is there properly, etc.

**Comment by mebrunet** [comment]
Weird... so the POST requests return a `{"r":0}`? Maybe it's a JSON formatting or encryption thing. Is the payload text identical between Chrome and Safari?

**Comment by anthonywebb** [comment]
Yea, the json payload is the same, I cant see the raw safari packet/headers etc.  I did spent a couple hours last night testing various combinations of headers from tutorials around the web, but didnt find a combo that worked.  Attached is a screenshot from safari with the return:

<img width="746" alt="screen shot 2015-08-27 at 5 08 26 pm" src="https://cloud.githubusercontent.com/assets/4397/9551573/3ffb487e-4d6f-11e5-91bd-a84ca2e2d355.png">

**Comment by mebrunet** [comment]
Somehow we need access to the raw underlying request. 

I'm really not a Mac guy... I also run Ubuntu which makes installing Safari hard, so unfortunately I need your help there. If the development tools don't show you, then switch the POST url (192.168.0.1/configure-ap) out for http://httpbin.org/post. The response will be a JSON object including all the information about the request sent. That should help us see what is actually happening.

**Comment by anthonywebb** [comment]
Happy to help.  Currently I am getting this error:
XMLHttpRequest cannot load http://httpbin.org/post. Origin
http://sevenblue.com is not allowed by Access-Control-Allow-Origin.

**Comment by mebrunet** [comment]
That's very strange... It looks like a CORS error, which is weird because httpbin replies with `Access-Control-Allow-Origin: YOUR_ORIGIN`.

Anyway, having toyed with this a bit, I'm thinking Safari might be changing the Content-Type headers... since we're not actually sending `multipart/form-data`. We really need to see that request & it's headers. Maybe this [link](http://stackoverflow.com/questions/26054732/how-to-inspect-http-requests-in-safari-8) can help?

**Comment by anthonywebb** [comment]
I am trying to find a way to view the actual RAW request headers, safari likes to parse and present stuff, wish I could just see the raw data!

In an effort to make the safari dump look like the chrome dump I added this:

xmlhttp.open('POST', url, true); //true specifies async
xmlhttp.timeout = 4000;
xmlhttp.setRequestHeader('Content-Type', 'multipart/form-data');
xmlhttp.setRequestHeader('Accept-Language', 'en-US,en;q=0.8');
xmlhttp.setRequestHeader('Accept', '*/*');

**Comment by mebrunet** [comment]
Great, and ya be sure to find out what is actually requested, not just what is specified in code. 

Also, I get that the `configure-ap` returns as expected... but what happens when the `connect-ap` call is made?

**Comment by anthonywebb** [comment]
connect-ap returns valid json too
[image: Inline image 1]

**Comment by mebrunet** [comment]
Okay but does the device restart and try to connect?

P.S. Image didn't make it.

**Comment by anthonywebb** [comment]
Yes, it restarts but it never blinks green, like it never stored any
credentials, goes right black to blinking blue.

**Comment by mebrunet** [comment]
Okay. It must be something with the headers and/or the way the JSON is being encoded and passed. :S Let me know when you figure out how to see that underlying request.

**Comment by mebrunet** [comment]
Hey @anthonywebb what version of the firmware did you compile this into?

**Comment by anthonywebb** [comment]
@mebrunet this is not compiled into any firmware, I simply hosted the src folder on my server and am using the 4.4 public firmware.  I have to compile my code against their cloud because I am a beta tester for the new particle dashboard.

**Comment by bradorego** [comment]
After browserifying softap.js according to [brewnerd's instructions](https://github.com/brewnerd/softap-setup-js#browserify) and then compiling into an Ionic app (Running on iOS 8.4.1 on an iPad Mini), I got the following errors:
![screen shot 2015-09-15 at 1 08 51 pm](https://cloud.githubusercontent.com/assets/1500840/9885510/1bf0dd50-5bab-11e5-8f6b-5fce0114978f.png)

The line in question (mind you this is in the browserified version):
![screen shot 2015-09-15 at 1 09 44 pm](https://cloud.githubusercontent.com/assets/1500840/9885511/1bf807c4-5bab-11e5-9636-2c256e41d32d.png)

I know very little about how this library is actually working, or the stuff Safari is complaining about, so if anyone else knows and can chime in before I start doing a deep dive, feel free :)

**Comment by brewnerd** [comment]
@mebrunet Photon 4.4 firmware **doesn't** return `YOUR_ORIGIN` for `Access-Control-Allow-Origin` on the POST /configure-ap... it returns `Access-Control-Allow-Origin: *`. I'm not sure if the wildcard here is relevant, but I thought I'd point it out. I'm also debugging Safari on iOS.

**Comment by mebrunet** [comment]
@brewnerd The wildcard vs. having your actual origin specified shouldn't change anything... at least not according to any of the resources I've consulted on CORS. 

@anthonywebb I was also on the private beta test of the dashboard. Not sure why that changes your ability to flash this into the Photons... Have you run into problems using custom firmware?

I'll be putting more time into debugging the iOS safari issue this week!

**Comment by anthonywebb** [comment]
@mebrunet yes I was having issue with custom firmware and was told to only use the stock setup with cloud compiled code.  This was very early on in the beta though and may have been resolved.  I'd like to avoid having to flash custom firmware to all the devices that go out the door.  We are using the photon in a consumer product and need to make it as easy as possible to manage.  I honestly cant believe that particle hasnt come up with a solid/easy way for a consumer to connect their device to the cloud.

**Comment by msolters** [comment]
@mebrunet There is a difference between anonymous origin access and whitelisted origin access.

Anonymous Origin
```
  Access-Control-Allow-Origin: *
```
If the server is using this in the response header, you cannot make a request to the server where the credentials flag is set in the request!!  Now, depending on the tool you are using to send messages (`http` module vs `http-browserify` module vs `http-browserify-xdr` module vs ....) *that is not guaranteed*.  Some set the credentials flag to true by default.  Some set it to false.

Whitelist Origin(s)
```
  Access-Control-Origin-Allow: YOUR_ORIGIN
```
This *can* work together with requests that have the credentials flag set.

---
In a nutshell, when the `http` module gets browserified, we need to study the source of `http-browserify`.  So if the server is responding with anonymous origin allowance, we MUST ensure that it is sending out requests with the credentials flag missing.  But, if we look at `http-browserify/lib/request.js`

```js
  if (typeof params.withCredentials === 'undefined') {
      params.withCredentials = true;
  }

  try { xhr.withCredentials = params.withCredentials }
  catch (e) {}
```

So, if you set `opts.withCredentials = false;` in your request, you can ensure your request will arrive.

I have [a fork of `softap-setup`](https://github.com/msolters/softap-setup-js/blob/1e2e60b271d06641fc907100157924bed573149e/softap.js) where I replaced the `http` module with `xhr` module (IE8+).  This makes setup on Safari work!
```js
SoftAP.prototype.__httpRequest = function __httpRequest(cmd, data, error) {

	var sock;
	var payload;
	var errorMessage = undefined;

	if(!cmd || typeof cmd !== "object") {
		errorMessage = "Invalid command object specified.";
	}
	if(errorMessage) { throw new Error(errorMessage); }

	var opts = {
		method: 'GET',
		url: 'http://' + this.host + '/' + cmd.name,
		withCredentials: false
	};

	if((cmd.body) && typeof cmd.body === 'object') {
		opts.body = JSON.stringify( cmd.body );
		opts.headers = { 'Content-Type': 'multipart/form-data', 'Accept': '*/*' };
		opts.method = 'POST';
	}
	
	xhr( opts, function(err, resp, body) {
		if (err) {
			console.error( err );
		}
		data(body);
	} );

	return;
};
```

The only browser/network combo that this doesn't work on is Safari *with secure networks only*.  Open networks are received fine, the credentials are saved, and the Photon automatically connects.  I got the `multipart/form-data` idea from @anthonywebb as per the firmware [issue discussion here](https://github.com/spark/firmware/issues/635).

If I can just get this method to work when `opts.body` also has a `.pwd`, we'd have complete coverage of the SoftAPSetup lib.

**Comment by msolters** [comment]
You can check other commits in that fork for a million other attempts at varying header parameters, method types and body encoding.  The above is the only thing I can hit upon that actually made progress - the Photon receives data from Safari *and actually does stuff with it.*

**Comment by mebrunet** [comment]
K - @msolters I figured the iOS/Safari issues were CORS related, but I didn't know that stuff about *whitelisted* vs *anonymous*. 

I've been giving my clients a PhoneGap app with the wifi connection process integrated into their account setup, and I haven't had any issues (when running firmware v0.4.5) as of yet.  Recall this Setup Page was really built to be embedded into the firmware (which would solve all the CORS issues), not as a separate website. When compiled into v0.4.4 it seemed to work fine across devices. I haven't tried embedding it into 0.4.5, but I imagine that would work fine.

As for the mobile web version of our app, I haven't had the bandwidth to debug on Safari yet. I've just been telling people "we're in beta, use chrome", haha. So let me know how this progresses. I'm hoping to put some time into figuring it out at the end of the month.
